// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrS5YARgv2xTZdhtA2_9XPzUMR8KUx8S0',
    appId: '1:524508495910:web:c7fd4c1886a25740bda6e7',
    messagingSenderId: '524508495910',
    projectId: 'flutter-yummy-milktea-shop',
    authDomain: 'flutter-yummy-milktea-shop.firebaseapp.com',
    storageBucket: 'flutter-yummy-milktea-shop.appspot.com',
    measurementId: 'G-GZL66M5MFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNqc4GKpPGFy2-l9LHXdwlpqqJFNmVjdU',
    appId: '1:524508495910:android:4bfceedcd8a93004bda6e7',
    messagingSenderId: '524508495910',
    projectId: 'flutter-yummy-milktea-shop',
    storageBucket: 'flutter-yummy-milktea-shop.appspot.com',
  );
}
